# Generated by Django 2.0.4 on 2018-08-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='What_i_want',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.TextField()),
                ('item_rating', models.CharField(max_length=100)),
                ('item_price', models.CharField(max_length=100)),
            ],
        ),
    ]
